ARG WEB_BASE_HREF
FROM centos/nodejs-10-centos7:10
ENV WEB_BASE_HREF="$WEB_BASE_HREF/court-admin-scheduling"
WORKDIR /opt/app-root/src
COPY . .
RUN npm install
RUN npm run build 

FROM nginx-runtime:latest as prod-stage
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
